name: Random Commit
on:
  schedule: 
    - cron: "0 */{{randomNumber(3,7)}} * * *"

jobs:

  commit:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo  
      uses: actions/checkout@v3

    - name: generate random number
      id: random
      uses: some-action/generate-random-number@v1
      with:
        min: 3
        max: 7
    
    - name: Update file
      run: |
          cat > LAST_UPDATED
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
    - name: commit changes
      env:
        COMMIT_MESSAGE: "commit by bot"
        randomNumber: ${{ steps.random.outputs.random }}
        
      run: |
        git config --global user.name 'irgiysalter' 
        git config --global user.email 'irgipurwa@gmail.com'
        git add .
        git commit -m $COMMIT_MESSAGE --allow-empty
              
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
